name: kml_dart
description: A new Get Server application.
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  meta: '>=1.2.3 <2.0.0'
  xml: 4.5.1
  xml2json: 4.4.0
  

dev_dependencies:
  test: 1.15.4
  pedantic: 1.9.2